export const surpriseMePrompts = [
  'a majestic dragon flying over a medieval castle at sunset with its wings spread wide',
  'a futuristic cityscape with flying cars and neon lights illuminating the night sky',
  'a robot chef meticulously preparing a gourmet meal in a high-tech kitchen with advanced appliances',
  'a magical forest filled with glowing mushrooms and fairies fluttering around in the moonlight',
  'a steampunk airship sailing through the clouds with intricate gears and steam engines',
  'a group of penguins having a lively beach party in Hawaii, complete with surfboards and tropical drinks',
  'a cyberpunk detective investigating a crime scene in a dark alley with neon signs flickering',
  'a giant octopus attacking a pirate ship in stormy seas, its tentacles wrapping around the mast',
  'a superhero flying over a bustling metropolis, cape billowing in the wind as they patrol the city',
  'a serene mountain landscape with a crystal-clear lake reflecting the snow-capped peaks',
  'a time traveler exploring ancient Egypt, marveling at the pyramids and hieroglyphics',
  'a whimsical treehouse village nestled in the treetops, connected by rope bridges and ladders',
  'a space explorer discovering a new alien planet with strange flora and fauna',
  'a fantasy castle surrounded by a moat and drawbridge, with banners fluttering in the breeze',
  'a group of adventurers battling a fearsome dragon in a dark and treacherous dungeon',
  'a futuristic robot butler serving drinks at a lavish party, its movements precise and graceful',
  'a mystical unicorn grazing in a meadow filled with colorful flowers and sparkling streams',
  'a pirate treasure map with hidden clues leading to a buried chest of gold and jewels',
  'a haunted mansion on a dark and stormy night, with ghostly apparitions and eerie sounds',
  'a wizard casting a powerful spell in a magical library filled with ancient tomes and artifacts',
  'a mermaid swimming gracefully in an underwater city, surrounded by coral reefs and sea creatures',
  'a knight in shining armor rescuing a princess from a towering castle, sword drawn and ready',
  'a spaceship landing on a distant moon, its crew stepping out to explore the alien landscape',
  'a fairy tale village with cobblestone streets and charming cottages, bustling with activity',
  'a ninja sneaking through a dense bamboo forest, moving silently and swiftly',
  'a carnival with colorful rides and games, the air filled with laughter and music',
  'a detective solving a mystery in a noir city, piecing together clues in the dimly lit streets',
  'a samurai warrior meditating in a tranquil zen garden, surrounded by cherry blossoms',
  'a futuristic sports car racing through a neon-lit city, its engine roaring and lights flashing',
  'a giant robot defending a city from monstrous creatures, its metal fists clashing with their scales',
  'a fantasy landscape with floating islands and cascading waterfalls, bathed in ethereal light',
  'a superhero team assembling for a mission, each member showcasing their unique powers',
  'a dragon hatching from an egg in a dark cave, its scales glistening in the dim light',
  "A serene lakeside at sunset, reflecting the vibrant colors of the sky, devoid of any human presence.",
  "An ancient, overgrown temple in a dense jungle, illuminated by the soft light of early morning.",
  "A bustling cyberpunk cityscape at night, bathed in neon lights, with flying cars zooming past towering skyscrapers.",
  "A majestic mountain range under the cloak of night, lit only by a full moon and a blanket of stars.",
  "A quaint cobblestone street in a historic European town, with flowers blooming on balconies, captured in golden hour lighting.",
  "An astronaut exploring a mysterious alien landscape, with strange vegetation and a distant planet rising in the sky.",
  "A serene winter scene of a snow-covered forest, with a cozy cabin lit by firelight, free of man-made structures.",
  "A vibrant coral reef teeming with colorful marine life, illuminated by the clear, sunlit waters above.",
  "A futuristic laboratory with advanced technology and gadgets, devoid of any human presence, under harsh daylight.",
  "A medieval knight standing on a foggy battlefield at dawn with intricate armor and mist surrounding them.",
  "A peaceful Zen garden at dawn, with perfectly raked sand, blooming cherry blossoms, and a gently flowing stream.",
  "A grand library filled with ancient books and magical artifacts, lit by the warm glow of candlelight.",
  "An enchanted forest pathway, lit by bioluminescent plants and fairy lights, leading to a hidden glade.",
  "A post-apocalyptic cityscape reclaimed by nature, with wild animals wandering amongst the ruins under overcast skies.",
  "A high fantasy castle floating among the clouds at sunset, surrounded by flying mythical creatures.",
  "An undersea city with futuristic architecture, glowing with artificial brightness from within, surrounded by the dark depths of the ocean.",
  "A vintage 1920s speakeasy bar, bustling with elegantly dressed patrons, in the soft, muted lighting of the era.",
  "A lone tree standing in the middle of a desert, under the harsh light of midday, casting a long shadow on the sand.",
  "A space station orbiting a distant earth-like planet, viewed from the perspective of an approaching spaceship, under the cloak of night.",
  "A traditional Japanese tea ceremony taking place in a tranquil bamboo forest, illuminated by the soft morning radiance.",
  'a magical portal opening to another dimension, swirling with vibrant colors and energy',
  'a group of astronauts exploring a distant galaxy, marveling at the wonders of the universe',
  'a steampunk inventor working on a new creation in a cluttered workshop filled with gadgets',
  'a haunted forest with ghostly apparitions and twisted trees, shrouded in mist',
  'a futuristic city with towering skyscrapers and flying vehicles zipping through the air',
  'a medieval market square bustling with activity, merchants selling their wares and townsfolk chatting',
  'a group of wizards dueling with magical spells, their wands crackling with energy',
  'a pirate ship sailing through a tropical paradise, its crew singing sea shanties',
  'a robot uprising in a dystopian future, machines rebelling against their human creators',
  'a fantasy kingdom with a majestic castle perched on a hill, overlooking the realm',
  'a superhero battling a giant monster in the city, buildings crumbling around them',
  'a time traveler visiting a futuristic metropolis, marveling at the advanced technology',
  'a dragon rider soaring through the skies, the wind rushing past as they navigate the clouds',
  'a magical academy with students learning spells and potions, their wands glowing with power',
  'a space station orbiting a distant planet, its crew conducting experiments in zero gravity',
  'a group of adventurers exploring a hidden temple, uncovering ancient secrets and treasures',
  'a futuristic city park with advanced technology, children playing with robotic companions',
  'a majestic dragon flying over a medieval castle at sunset with its wings spread wide',
  'a futuristic cityscape with flying cars and neon lights illuminating the night sky',
  'an enchanted forest glowing with bioluminescent plants and mysterious creatures under a full moon',
  'a cyberpunk character in a rain-soaked alley, with neon signs reflecting off puddles',
  'a tranquil beach at sunrise with crystal-clear water and soft golden sands',
  "a space station orbiting Saturn, with the planet’s rings visible in the background",
  'a lone samurai standing in a field of cherry blossoms, his sword gleaming under the moonlight',
  'a surreal landscape with floating islands and waterfalls cascading into the clouds',
  'a steampunk-inspired airship soaring through a vibrant orange and pink sky',
  'a rustic cabin in the woods during a snowy winter evening, smoke rising from the chimney',
  'an underwater city illuminated by glowing coral and schools of bioluminescent fish',
  'a close-up of a delicate flower covered in morning dew, with vibrant petals and sharp details',
  'a bustling market in a Middle Eastern desert city, filled with vibrant colors and textures',
  'a futuristic humanoid robot in a sleek, high-tech laboratory with glowing blue lights',
  'a serene mountain lake reflecting the surrounding pine trees and snow-capped peaks',
  'an astronaut planting a flag on an alien planet with a vibrant, colorful atmosphere',
  'a gothic cathedral with intricate stained glass windows, lit by golden sunlight streaming in',
  'a mysterious ancient ruin in the jungle, overgrown with vines and hidden artifacts',
  'a spaceship cockpit with a view of a massive starburst in deep space',
  'a fairytale castle perched on a hill surrounded by fields of wildflowers under a blue sky',
  'a close-up portrait of a tiger, its eyes glowing in the dim light of the forest',
  'a rustic European village nestled in a valley, with cobblestone streets and warm lights',
  'a fantasy battle between knights and orcs in a rain-soaked battlefield under a stormy sky',
  'a dystopian city skyline dominated by towering skyscrapers and industrial haze',
  'a serene Zen garden with perfectly raked gravel and bonsai trees surrounded by a stone wall',
  'a desert caravan traveling under a star-filled night sky, led by camels and lanterns',
  'a Viking longship navigating through icy waters surrounded by towering glaciers',
  'a painter’s studio filled with vibrant canvases, brushes, and paint splatters on the walls',
  'a futuristic soldier in power armor standing on a battlefield with distant explosions',
  'a lush jungle waterfall cascading into a pool surrounded by tropical vegetation',
  'a retro diner at night with glowing neon signs and vintage cars parked outside',
  'a magical library with towering bookshelves, floating candles, and glowing orbs of light',
  'a black-and-white portrait of a mysterious detective in a fedora with a cigarette in hand',
  'a serene lavender field stretching into the horizon under a vibrant sunset',
  'a Victorian tea party in an ornate garden with elegant dresses and fine china',
  'a dark, eerie forest with twisted trees and a glowing lantern hanging from a branch',
  'a futuristic underwater research station with glowing windows and exotic marine life outside',
  'a cozy café on a rainy day with warm lights reflecting on the wet cobblestones outside',
  'a samurai duel at dawn in a misty bamboo forest with rays of sunlight piercing through',
  'a surreal dreamscape with melting clocks and floating islands inspired by Salvador Dalí',
  'a carnival at night, with vibrant lights, spinning rides, and colorful fireworks in the sky',
  'a bustling cyberpunk marketplace with robotic vendors and holographic advertisements',
  'a serene meadow with grazing deer, wildflowers, and a soft golden glow at sunrise',
  'a detailed close-up of a butterfly resting on a vibrant flower with intricate wing patterns',
  'a sci-fi alien world with floating monoliths, strange vegetation, and two suns in the sky',
  'a medieval blacksmith working in a forge, sparks flying as he hammers glowing metal',
  'a grand ballroom with a crystal chandelier, polished floors, and elegantly dressed dancers',
  'a mysterious lighthouse on a rocky cliff with waves crashing below and a stormy sky above',
  'a futuristic flying train speeding through a neon-lit cityscape at night',
  'a peaceful snowy village during Christmas, with warm lights glowing in every window'
];